### ISSUE TITLE
Waveform files missing?

### ISSUE THREAD

**Issue by mathiasbockwoldt** [alanlhutchison/empirical-JTK_CYCLE-with-asymmetry#1]
I just tried to get the extended JTK_cycle started. Unfortunately, the help texts don't help me enough to start the script. I can find asymmetries and periods in ref_files/ and guess what they are used to, but I could no find any waveform files or a hint on how to create such files. The waveforms default value (trough) led to a file-not-found error:
```
Traceback (most recent call last):
  File "./jtk7.py", line 551, in <module>
    main(args)
  File "./jtk7.py", line 48, in main
    waveforms = read_in_list(fn_waveform)
  File "./jtk7.py", line 111, in read_in_list
    with open(fn,'r') as f:
IOError: [Errno 2] No such file or directory: 'trough'
```
The same error occurs for any of the suggested included files (cosine (dflt), rampup, rampdown, impulse, step, trough). By the way, according to the help text (./jtk7.py -h), the default value is "cosine", although it is in fact "trough".

How do I include an appropriate waveform file?

**Comment by alanlhutchison** [comment]
Hi Mathias,

You are right on both counts! I have added a reference waveform file, which just has the name of the waveform in it (the idea is if you wanted to do both cosine and trough in the same analysis, you could include each on a separate line in the same file). I have also changed the default behavior to cosine as it says in the documentation. Thank you for pointing these both out to me!

Please let me know if you have any more questions or comments.

Alan

**Comment by laloumdav** [comment]
Hello!

Acrtually I did not succeed in using several waveforms in the same analysis as it is notified (waveform_file : "_Should be a file with waveforms  you wish to search for listed in a single column separated by newlines_"). 
Appart from _cosine_ and _trough_ waveforms, other waveforms are not working,
 since it is specified we could use other waveform choices as :["waveform_cosine.txt","waveform_rampup.txt","waveform_rampdown.txt","waveform_step.txt","waveform_impulse.txt","waveform_trough.txt"]

Did I miss something ? 
Waiting for your help 

David
