### ISSUE TITLE
Error with all zero columns

### ISSUE THREAD

**Issue by aleccrowell** [alanlhutchison/empirical-JTK_CYCLE-with-asymmetry#3]
I just wanted to make you aware of a slightly cryptic error I was receiving.  I was able to figure it out as it seems to be produced by rows which contain all zeros in the input file which is very easy to rectify once you know what's going on as these obviously aren't of interest anyway.  The error message is:

`Traceback (most recent call last):
  File "/Users/user4574/empirical-JTK_CYCLE-with-asymmetry/eJTK-CalcP.py", line 132, in <module>
    main(args)
  File "/Users/user4574/empirical-JTK_CYCLE-with-asymmetry/eJTK-CalcP.py", line 31, in main
    fn_out,fn_null_out = eJTK.main(args)
  File "/Users/user4574/empirical-JTK_CYCLE-with-asymmetry/bin/eJTK.py", line 85, in main
    best = a_get_best_match(serie,waveform,triples,dref,new_header)
  File "accessories.pyx", line 119, in accessories.get_best_match (accessories.c:3618)
    r = pick_best_match(res)
  File "accessories.pyx", line 96, in accessories.pick_best_match (accessories.c:2924)
    phasemask = (min(phases)==phases)
ValueError: min() arg is an empty sequence`

Anyways thanks for a great tool.

**Comment by alanlhutchison** [comment]
Hi alecrowell,

Thanks for reminding me of this issue. I believe I have fixed it, so hopefully it doesn't bother you or anyone again.
