### ISSUE TITLE
compiling issue?

### ISSUE THREAD

**Issue by yuchaojiang** [alanlhutchison/empirical-JTK_CYCLE-with-asymmetry#7]
Hi, I was trying to compile and run eJTK and encountered the error below. Could you please help?

Thanks!

Yuchaos-MacBook-Pro:bin yuchaojiang$ python setup.py build_ext --inplace
Compiling accessories.pyx because it changed.
[1/1] Cythonizing accessories.pyx
running build_ext
building 'accessories' extension
creating build
creating build/temp.macosx-10.7-x86_64-3.6
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/include/python3.6m -c accessories.c -o build/temp.macosx-10.7-x86_64-3.6/accessories.o
accessories.c:2019:7: warning: variable '__pyx_v_y' is used uninitialized whenever 'if' condition is false
      [-Wsometimes-uninitialized]
  if (__pyx_t_5) {
      ^~~~~~~~~
accessories.c:2148:34: note: uninitialized use occurs here
  __pyx_t_1 = PyFloat_FromDouble(__pyx_v_y); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 46, __pyx_L1_error)
                                 ^~~~~~~~~
accessories.c:2019:3: note: remove the 'if' if its condition is always true
  if (__pyx_t_5) {
  ^~~~~~~~~~~~~~~
accessories.c:1849:19: note: initialize the variable '__pyx_v_y' to silence this warning
  double __pyx_v_y;
                  ^
                   = 0.0
accessories.c:2352:7: warning: variable '__pyx_v_y' is used uninitialized whenever 'if' condition is false
      [-Wsometimes-uninitialized]
  if (__pyx_t_5) {
      ^~~~~~~~~
accessories.c:2403:34: note: uninitialized use occurs here
  __pyx_t_3 = PyFloat_FromDouble(__pyx_v_y); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 57, __pyx_L1_error)
                                 ^~~~~~~~~
accessories.c:2352:3: note: remove the 'if' if its condition is always true
  if (__pyx_t_5) {
  ^~~~~~~~~~~~~~~
accessories.c:2249:19: note: initialize the variable '__pyx_v_y' to silence this warning
  double __pyx_v_y;
                  ^
                   = 0.0
accessories.c:12606:26: warning: code will never be executed [-Wunreachable-code]
                module = PyImport_ImportModuleLevelObject(
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings generated.
gcc -bundle -undefined dynamic_lookup -L/anaconda3/lib -arch x86_64 -L/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/accessories.o -o /Users/yuchaojiang/Dropbox/circadian_benchmark/empirical-JTK_CYCLE-with-asymmetry-master/bin/accessories.cpython-36m-darwin.so

Yuchaos-MacBook-Pro:bin yuchaojiang$ cd ..
Yuchaos-MacBook-Pro:empirical-JTK_CYCLE-with-asymmetry-master yuchaojiang$ ls
LICENSE.txt	README.md	bin		eJTK-CalcP.py	example		previous_files	ref_files
Yuchaos-MacBook-Pro:empirical-JTK_CYCLE-with-asymmetry-master yuchaojiang$ ./eJTK-CalcP.py -f example/TestInput4.txt -w ref_files/waveform_cosine.txt -p ref_files/period24.txt -s ref_files/phases_00-22_by2.txt -a ref_files/asymmetries_02-22_by2.txt -x cos24_ph00-22_by2_a02-22_by2_OTHERTEXT
Traceback (most recent call last):
  File "./eJTK-CalcP.py", line 18, in <module>
    import eJTK
  File "./bin/eJTK.py", line 27
    print 'Did you run python setup.py build_ext --inplace in the bin directory?'
                                                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Did you run python setup.py build_ext --inplace in the bin directory?')?

**Comment by Zhiwen-Owen-Jiang** [comment]
Hi Yuchao,
I know how to deal with it. You just need to copy eJTK-CalcP.py to bin folder and compile again.

**Comment by davwong47** [comment]
The error shows that it does not understand the "print" command without parentheses. This is because you need to run this using python version 2.7. Create a new conda environment with python 2.7, install the required packages and try again - that should work!
